aargh

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,8 +14,8 @@ jobs:
           echo "${GITHUB_REF}"
 
           docker-compose pull -q redis postgres
-          docker pull -q ghcr.io/alephdata/ingest-file:cache || 0
-          docker pull -q ghcr.io/alephdata/convert-document:cache || 0
+          docker pull -q ghcr.io/alephdata/ingest-file:cache || echo "pull fail"
+          docker pull -q ghcr.io/alephdata/convert-document:cache || echo "pull fail"
       - name: Start services
         run: |
           make services
